apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbshop-ingress
  namespace: qbshop
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - asriv.shop
    secretName: qbshop-tls-secret  # Cert-Manager will manage this
  rules:
  - host: asriv.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qbshop-service
            port:
              number: 80

