apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: qbshop
spec:
  template:
    spec:
      containers:
      - name: qbs-migration
<<<<<<< HEAD
        image: satyamsri/qbshop-migration:latest
=======
        image: satyamsri/qbshop-migration:7
>>>>>>> 19c8451925e51327c62a233a40d6c98bccd1a7fc
        imagePullPolicy: Always
        env:
        - name: MONGODB_URI
          value: "mongodb://mongodb-service:27017/easyshop"
      restartPolicy: OnFailure
